{
    'name': 'My Queue Job',
    'version': '16.0.1.0.0',
    'summary': """k""",
    'description': """k""",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': "https://cybrosys.com/",
    'depends': ['base','mail','queue_job','web'],
    'data': ['security/ir.model.access.csv',
             'data/sheduled_date.xml',
             'data/job_schedule_action.xml',
             'views/my_model.xml',
             'views/recipients_email_view.xml'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
